import { Product } from "./product";

export class ProductList{
    productList:Product[]=[
        {id:1,name:'Dell',price:3000,stars:'4',category:'Bilgisayar',image:'1.jpg'},
        {id:2,name:'Nike',price:1000,stars:'3',category:'Ayakkabı',image:'14.jpg'},
        {id:3,name:'Xiaomi Redmi 5',price:1000,stars:'3',category:'Telefon',image:'3.jpg'},
        {id:4,name:'Apple Watch',price:3500,stars:'5',category:'Aksesuar',image:'4.jpg'},
        {id:5,name:'Tişört',price:30,stars:'4',category:'Giyim',image:'5.jpg'},
        {id:6,name:'Deodorant',price:55,stars:'2',category:'Kozmetik',image:'6.jpg'},
        {id:7,name:'Skechers',price:500,stars:'4',category:'Ayakkabı',image:'7.jpg'},
        {id:8,name:'Lenovo',price:3500,stars:'1',category:'Bilgisayar',image:'8.jpg'},
        {id:9,name:'Macbook',price:8000,stars:'4',category:'Bilgisayar',image:'9.jpg'},
        {id:10,name:'Samsung s6',price:2000,stars:'2',category:'Telefon',image:'10.jpg'},
        {id:11,name:'Gümüş Kolye',price:100,stars:'3',category:'Aksesuar',image:'11.jpg'},
        {id:12,name:'Jean',price:100,stars:'5',category:'Giyim',image:'12.jpg'},
        {id:13,name:'Parfüm',price:120,stars:'4',category:'Kozmetik',image:'13.jpg'},
        {id:14,name:'Adidas',price:300,stars:'3',category:'Ayakkabı',image:'14.jpg'},
        {id:15,name:'Puma',price:200,stars:'4',category:'Ayakkabı',image:'15.jpg'},
        {id:16,name:'Iphone x',price:10000,stars:'4',category:'Telefon',image:'16.jpg'},
        {id:17,name:'Huwaie P20',price:3000,stars:'5',category:'Telefon',image:'17.jpg'},
        {id:18,name:'Deri Cüzdan',price:100,stars:'3',category:'Aksesuar',image:'18.jpg'},
        {id:19,name:'Mont',price:220,stars:'4',category:'Giyim',image:'19.jpg'},
        {id:20,name:'Makyaj Seti',price:120,stars:'1',category:'Kozmetik',image:'20.jpg'},
        {id:21,name:'Bot',price:250,stars:'5',category:'Ayakkabı',image:'21.jpg'},
        {id:22,name:'Dell',price:3000,stars:'4',category:'Bilgisayar',image:'1.jpg'},
        {id:23,name:'Asus',price:5000,stars:'3',category:'Bilgisayar',image:'2.jpg'},
        {id:24,name:'Xiaomi Redmi 5',price:1000,stars:'3',category:'Telefon',image:'3.jpg'},
        {id:25,name:'Apple Watch',price:3500,stars:'5',category:'Aksesuar',image:'4.jpg'},
        {id:26,name:'Tişört',price:30,stars:'4',category:'Giyim',image:'5.jpg'},
        {id:27,name:'Deodorant',price:55,stars:'2',category:'Kozmetik',image:'6.jpg'},
        {id:28,name:'Skechers',price:500,stars:'4',category:'Ayakkabı',image:'7.jpg'},
        {id:29,name:'Lenovo',price:3500,stars:'1',category:'Bilgisayar',image:'8.jpg'},
        {id:30,name:'Macbook',price:8000,stars:'4',category:'Bilgisayar',image:'9.jpg'},
        {id:31,name:'Samsung s6',price:2000,stars:'2',category:'Telefon',image:'10.jpg'},
        {id:32,name:'Gümüş Kolye',price:100,stars:'3',category:'Aksesuar',image:'11.jpg'},
        {id:33,name:'Jean',price:100,stars:'5',category:'Giyim',image:'12.jpg'},
        {id:34,name:'Parfüm',price:120,stars:'4',category:'Kozmetik',image:'13.jpg'},
        {id:35,name:'Adidas',price:300,stars:'3',category:'Ayakkabı',image:'14.jpg'},
        {id:36,name:'Puma',price:200,stars:'4',category:'Ayakkabı',image:'15.jpg'},
        {id:37,name:'Iphone x',price:10000,stars:'4',category:'Telefon',image:'16.jpg'},
        {id:38,name:'Huwaie P20',price:3000,stars:'5',category:'Telefon',image:'17.jpg'},
        {id:39,name:'Deri Cüzdan',price:100,stars:'3',category:'Aksesuar',image:'18.jpg'},
        {id:40,name:'Mont',price:220,stars:'4',category:'Giyim',image:'19.jpg'},
        {id:41,name:'Makyaj Seti',price:120,stars:'1',category:'Kozmetik',image:'20.jpg'},
        {id:42,name:'Bot',price:250,stars:'5',category:'Ayakkabı',image:'21.jpg'},
        {id:43,name:'Makyaj Seti',price:120,stars:'1',category:'Kozmetik',image:'20.jpg'},
        {id:44,name:'Bot',price:250,stars:'5',category:'Ayakkabı',image:'21.jpg'},
        {id:45,name:'Dell',price:3000,stars:'4',category:'Bilgisayar',image:'1.jpg'},
        {id:46,name:'Asus',price:5000,stars:'3',category:'Bilgisayar',image:'2.jpg'},
        {id:47,name:'Xiaomi Redmi 5',price:1000,stars:'3',category:'Telefon',image:'3.jpg'},
        {id:48,name:'Apple Watch',price:3500,stars:'5',category:'Aksesuar',image:'4.jpg'},
        {id:49,name:'Tişört',price:30,stars:'4',category:'Giyim',image:'5.jpg'},
        {id:50,name:'Deodorant',price:55,stars:'2',category:'Kozmetik',image:'6.jpg'},
        {id:51,name:'Skechers',price:500,stars:'4',category:'Ayakkabı',image:'7.jpg'},
        {id:52,name:'Lenovo',price:3500,stars:'1',category:'Bilgisayar',image:'8.jpg'},
        {id:53,name:'Macbook',price:8000,stars:'4',category:'Bilgisayar',image:'9.jpg'},
        {id:54,name:'Samsung s6',price:2000,stars:'2',category:'Telefon',image:'10.jpg'},
        {id:55,name:'Gümüş Kolye',price:100,stars:'3',category:'Aksesuar',image:'11.jpg'},
        {id:56,name:'Jean',price:100,stars:'5',category:'Giyim',image:'12.jpg'},
        {id:57,name:'Parfüm',price:120,stars:'4',category:'Kozmetik',image:'13.jpg'},
        {id:58,name:'Adidas',price:300,stars:'3',category:'Ayakkabı',image:'14.jpg'},
        {id:59,name:'Puma',price:200,stars:'4',category:'Ayakkabı',image:'15.jpg'},
        {id:60,name:'Iphone x',price:10000,stars:'4',category:'Telefon',image:'16.jpg'},
        {id:61,name:'Huwaie P20',price:3000,stars:'5',category:'Telefon',image:'17.jpg'},
        {id:62,name:'Deri Cüzdan',price:100,stars:'3',category:'Aksesuar',image:'18.jpg'},
        {id:63,name:'Mont',price:220,stars:'4',category:'Giyim',image:'19.jpg'},
        {id:64,name:'Makyaj Seti',price:120,stars:'1',category:'Kozmetik',image:'20.jpg'},
        {id:65,name:'Bot',price:250,stars:'5',category:'Ayakkabı',image:'21.jpg'},
        {id:66,name:'Deri Cüzdan',price:100,stars:'3',category:'Aksesuar',image:'18.jpg'},
        {id:67,name:'Mont',price:220,stars:'4',category:'Giyim',image:'19.jpg'},
        {id:68,name:'Makyaj Seti',price:120,stars:'1',category:'Kozmetik',image:'20.jpg'},
        {id:69,name:'Gümüş Kolye',price:100,stars:'3',category:'Aksesuar',image:'11.jpg'}
    ]
}